"""Export the SQLite ORM state into a flat SQL file loadable by Cloudflare D1.

Output: `edge/data.sql`
Usage:
    PYTHONPATH=. python -m app.export.to_d1

Shape note: the edge schema is a denormalised view designed for cheap reads.
- `recommendations` and `guru_mentions` carry player name/team/position so
  the Worker doesn't need to join.
- `accuracy_log` is precomputed per finished gameweek.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from app.core.config import ROOT_DIR
from app.db.models import (
    ActualResult,
    Gameweek,
    GuruMention,
    GuruSource,
    Player,
    PlayerGWStats,
    Recommendation,
    Team,
)
from app.db.session import SessionLocal
from app.services.recommendations import accuracy_for_gw


OUT = ROOT_DIR.parent / "edge" / "data.sql"


def _esc(v: Any) -> str:
    if v is None:
        return "NULL"
    if isinstance(v, bool):
        return "1" if v else "0"
    if isinstance(v, (int, float)):
        return repr(v)
    s = str(v).replace("'", "''")
    return f"'{s}'"


def _row(cols: list[str], values: list[Any]) -> str:
    return f"({', '.join(_esc(v) for v in values)})"


def _insert_many(
    out: list[str], table: str, cols: list[str], rows: list[list[Any]], batch: int = 200
) -> None:
    if not rows:
        return
    col_list = ", ".join(cols)
    for i in range(0, len(rows), batch):
        chunk = rows[i : i + batch]
        values = ",\n  ".join(_row(cols, r) for r in chunk)
        out.append(f"INSERT INTO {table} ({col_list}) VALUES\n  {values};")


def export() -> Path:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    # D1 rejects explicit BEGIN TRANSACTION / COMMIT in bulk imports — it wraps
    # the whole file in its own Durable Object transaction. Just emit bare DDL.
    lines: list[str] = [
        "-- Generated by app.export.to_d1. Do not edit by hand.",
        "DELETE FROM guru_mentions;",
        "DELETE FROM guru_sources;",
        "DELETE FROM accuracy_log;",
        "DELETE FROM actual_results;",
        "DELETE FROM recommendations;",
        "DELETE FROM player_gw_stats;",
        "DELETE FROM gameweeks;",
        "DELETE FROM players;",
        "DELETE FROM teams;",
    ]

    with SessionLocal() as db:
        teams = {t.id: t for t in db.query(Team).all()}
        # Filter teams to just the ones referenced by live-season players to keep
        # D1 small and the UI consistent.
        live_team_ids = {
            t_id for (t_id,) in db.query(Player.team_id).filter(
                Player.id >= 99990000, Player.id < 99999999
            ).distinct().all()
        }

        team_rows = [
            [t.id, t.name, t.short_name]
            for t in teams.values() if t.id in live_team_ids
        ]
        _insert_many(lines, "teams", ["id", "name", "short_name"], team_rows)

        players = (
            db.query(Player)
            .filter(Player.id >= 99990000, Player.id < 99999999)
            .all()
        )
        player_rows = [
            [
                p.id, p.web_name, p.first_name, p.second_name, p.position,
                p.team_id,
                teams[p.team_id].short_name if p.team_id in teams else None,
                teams[p.team_id].name if p.team_id in teams else None,
                round(p.now_cost / 10.0, 1),
                p.form, p.total_points,
                p.selected_by_percent, p.news or "",
            ]
            for p in players
        ]
        _insert_many(
            lines, "players",
            [
                "id", "web_name", "first_name", "second_name", "position",
                "team_id", "team_short", "team_name", "price", "form",
                "total_points", "selected_by_percent", "news",
            ],
            player_rows,
        )

        live_player_ids = {p.id for p in players}

        gws = db.query(Gameweek).order_by(Gameweek.id).all()
        gw_rows = [
            [
                g.id, g.name,
                g.deadline_time.isoformat() if g.deadline_time else None,
                int(bool(g.is_current)), int(bool(g.is_next)),
                int(bool(g.finished)), g.average_entry_score, g.highest_score,
            ]
            for g in gws
        ]
        _insert_many(
            lines, "gameweeks",
            [
                "id", "name", "deadline_time", "is_current", "is_next",
                "finished", "average_entry_score", "highest_score",
            ],
            gw_rows,
        )

        # Stats: only keep 3 seasons * live-season players for history charts
        stat_rows = []
        stats = (
            db.query(PlayerGWStats)
            .filter(PlayerGWStats.player_id.in_(live_player_ids))
            .all()
        )
        # The live-season player IDs may not match historical rows since
        # seed_offline uses season-scoped IDs. So also pull all stats where
        # player_id ranges for the 3 canonical seasons the Worker shows.
        # (If the portal is driven from real data, IDs align cleanly.)
        for s in stats:
            stat_rows.append([
                s.player_id, s.season, s.gw, s.minutes, s.goals_scored,
                s.assists, s.bonus, s.bps, s.expected_goals,
                s.expected_assists, s.total_points,
            ])
        _insert_many(
            lines, "player_gw_stats",
            [
                "player_id", "season", "gw", "minutes", "goals_scored",
                "assists", "bonus", "bps", "expected_goals",
                "expected_assists", "total_points",
            ],
            stat_rows,
        )

        recs = db.query(Recommendation).filter(Recommendation.season == "live").all()
        rec_rows = [
            [
                r.gw, r.season, r.player_id, r.position,
                round(float(r.predicted_points), 4),
                round(float(r.p10), 4), round(float(r.p90), 4),
                r.rank_in_position, int(bool(r.is_top_pick)),
                int(bool(r.is_captain)), int(bool(r.in_best_xi)),
                round(float(r.social_score), 4),
            ]
            for r in recs
        ]
        _insert_many(
            lines, "recommendations",
            [
                "gw", "season", "player_id", "position", "predicted_points",
                "p10", "p90", "rank_in_position", "is_top_pick", "is_captain",
                "in_best_xi", "social_score",
            ],
            rec_rows,
        )

        actuals = db.query(ActualResult).filter(ActualResult.season == "live").all()
        actual_rows = [
            [
                a.player_id, a.season, a.gw, a.actual_points, a.goals_scored,
                a.assists, int(bool(a.clean_sheet)), a.minutes, a.bonus,
            ]
            for a in actuals
        ]
        _insert_many(
            lines, "actual_results",
            [
                "player_id", "season", "gw", "actual_points", "goals_scored",
                "assists", "clean_sheet", "minutes", "bonus",
            ],
            actual_rows,
        )

        # Precompute accuracy per GW so the Worker doesn't have to
        acc_rows = []
        rec_gws = {r.gw for r in recs}
        for gw in sorted(rec_gws):
            acc = accuracy_for_gw(db, gw, "live")
            if acc.get("mae") is None:
                continue
            acc_rows.append([
                gw, "live",
                acc.get("mae"), acc.get("rmse"), acc.get("rank_corr"),
                acc.get("n"), acc.get("captain_actual"),
                acc.get("xi_realised"), acc.get("top_picks_hit"),
                acc.get("top_picks_total"),
            ])
        _insert_many(
            lines, "accuracy_log",
            [
                "gw", "season", "mae", "rmse", "rank_corr", "n",
                "captain_actual", "xi_realised", "top_picks_hit",
                "top_picks_total",
            ],
            acc_rows,
        )

        sources = db.query(GuruSource).all()
        source_rows = [[s.id, s.name, s.platform, s.handle, s.weight] for s in sources]
        _insert_many(lines, "guru_sources",
                     ["id", "name", "platform", "handle", "weight"], source_rows)

        source_map = {s.id: s for s in sources}
        player_map = {p.id: p for p in players}
        mentions = (
            db.query(GuruMention)
            .filter(GuruMention.player_id.in_(live_player_ids))
            .all()
        )
        m_rows = []
        for m in mentions:
            src = source_map.get(m.source_id)
            ply = player_map.get(m.player_id)
            if src is None or ply is None:
                continue
            m_rows.append([
                m.source_id, src.name, src.platform,
                m.player_id, ply.web_name, ply.position,
                m.gw, round(float(m.sentiment), 3),
                int(bool(m.is_captain_pick)), int(bool(m.is_avoid)),
                int(bool(m.is_differential)),
                (m.snippet or "")[:400],
                m.captured_at.isoformat() if m.captured_at else None,
            ])
        _insert_many(
            lines, "guru_mentions",
            [
                "source_id", "source_name", "platform", "player_id",
                "web_name", "position", "gw", "sentiment",
                "is_captain_pick", "is_avoid", "is_differential",
                "snippet", "captured_at",
            ],
            m_rows,
        )

    OUT.write_text("\n".join(lines))
    return OUT


if __name__ == "__main__":
    path = export()
    print(f"Wrote {path} ({path.stat().st_size / 1024:.1f} KB)")
